version: '3'
services:
  app:
    container_name: sweater-app
    image: springboot-postgresql
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    volumes:
      - ./pg_data:/var/lib/postgresql/data/pgdata
    environment:
      POSTGRES_HOST: db
      PGDATA: /var/lib/postgresql/data/pgdata

  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sweater
